[build]
  # Build command - use npm run build directly since we're not using complex caching
  command = "npm run build"
  
  # Output directory (where the built files are placed)
  publish = "dist"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18.17.0"
  
  # Enable faster builds
  NPM_FLAGS = "--silent --no-progress"

# Headers for better caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect - send all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
